apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/crd/bgppeers.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/crd/bfdprofiles.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/crd/ipaddresspools.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/crd/l2advertisements.yaml