apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: "0.13.10"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 1m
  install:
    createNamespace: false
  values: {}