apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openvpn
  namespace: openvpn
spec:
  releaseName: openvpn
  chart:
    spec:
      chart: openvpn
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: openvpn-values