apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: metallb
      version: "0.13.7"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  values:
    speaker:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
    controller:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists