apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../namespaces/openvpn.yaml
- ../../help-repositories/k8s-at-home.yaml
- ../../helm-releases/openvpn-release.yaml
