replicaCount: 2
image:
  repository: romandruzyk/solvify-web
  tag: latest
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  hosts:
    - host: druzyk.com
      paths:
        - path: /
          pathType: Prefix
  tls: []  # Добавьте TLS если нужно.